[package]
name = "dce"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bbb = { path = "../bbb" }

[dependencies.bril-rs]
path = "../bril-rs"
features = ["memory", "float", "ssa", "speculate"]
